---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: posts
  label: Posts
  create: documents
  match: "**/*.md"
upload_dir: ''
public_path: https://res.cloudinary.com/dy3alb7gv/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: _site
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npx eleventy --watch
