backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
site_url: "https://fruechtl.me"
media_folder: "src/images"
public_folder: "images"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Homepage"
        delete: false
        file: "index.njk"
        slug: "{{slug}}"
        create: false
        fields:
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "layouts/njk.njk",
            }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "SEO Meta Title",
              name: "metaTitle",
              widget: "string",
              required: false,
            }
          - {
              label: "SEO Meta Description",
              name: "metaDesc",
              widget: "string",
              required: false,
            }
          - {
              label: "Post Feed Heading",
              name: "postsHeading",
              widget: "string",
              default: "Latest posts",
            }
          - {
              label: "Archive Link Text",
              name: "archiveButtonText",
              widget: "string",
              default: "See all posts",
            }
          - {
              label: "Social Image",
              name: "socialImage",
              widget: "image",
              required: false,
            }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "posts"
    label: "Posts"
    folder: "journal"
    slug: "{{slug}}"
    preview_path: "journal/{{slug}}"
    create: true
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "layouts/post.njk",
        }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "SEO Meta Title",
          name: "metaTitle",
          widget: "string",
          required: false,
        }
      - {
          label: "SEO Meta Description",
          name: "metaDesc",
          widget: "string",
          required: false,
        }
      - {
          label: "Social Image",
          name: "socialImage",
          widget: "image",
          required: false,
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true }
      - { label: "Body", name: "body", widget: "markdown" }
